apiVersion: v1
data:
  application.properties: |+
  avinor.timetable.scheduler.consumer=quartz2://avinorTimetableScheduler?cron={{ .Values.avinorTimetableSchedulerCron }}
  avinor.airports.large=BGO,BOO,SVG,TRD
  blobstore.gcs.bucket.name={{ .Values.gcsBucketName}}
  avinor.realtime.arrivals.timeto=96
  spring.profiles.active=gcs-blobstore
  blobstore.provider.id=21
  blobstore.blob.path=inbound/received/avi/
  logging.level.com=INFO
  netex.generated.output.path=/deployments/data/netex
  avinor.timetable.feed.endpoint=https://flydata.avinor.no/XmlFeedScheduled.asp
  server.port=8776
  avinor.realtime.scheduler.options=cron=2+*/3+*+*+*+*+?&trigger.timeZone=Europe/Oslo
  avinor.airport.feed.endpoint=https://flydata.avinor.no/airportNames.asp
  avinor.timetable.dump.output.path=/deployments/data/dump
  camel.springboot.name=extime
  avinor.realtime.arrivals.timefrom=0
  spring.jmx.enabled=true
  queue.upload.destination.name=MardukInboundQueue
  netex.compressed.output.path=/deployments/data/zip
  avinor.timetable.min.range=7
  logging.level.no.rutebanken=DEBUG
  avinor.timetable.period.months=4
  blobstore.gcs.credential.path=/etc/exchange/marduk-exchange-blobstore-credentials.json
  avinor.realtime.departures.timefrom=0
  endpoints.jmx.enabled=true
  avinor.airline.feed.endpoint=https://flydata.avinor.no/airlineNames.asp
  blobstore.gcs.project.id={{ .Values.gcpProjectId }}
  avinor.realtime.feed.endpoint=https://flydata.avinor.no/XmlFeed.asp
  avinor.timetable.dump.enabled=false
  logging.level.org=INFO
  avinor.realtime.departures.timeto=72
  spring.main.sources=no.rutebanken.extime
  avinor.timetable.max.range=180
  spring.cloud.gcp.pubsub.project-id={{ .Values.gcpProjectId }}
  spring.cloud.gcp.pubsub.credentials.location=file:/etc/marduk-pubsub-account/marduk-pubsub-credentials.json
  spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
  spring.cloud.gcp.pubsub.subscriber.executor-threads=30
  spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=36000
  management.server.port=9001
  management.endpoints.enabled-by-default=false
  management.endpoint.info.enabled=true
  management.endpoint.health.enabled=true
  management.endpoint.prometheus.enabled=true
  management.endpoints.web.base-path=/
  management.endpoints.web.exposure.include=info,health,prometheus
kind: ConfigMap
metadata:
  name: {{ template "extime.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
