apiVersion: v1
data:
  application.properties: |+

    # Spring Boot
    spring.profiles.active=gcs-blobstore
    spring.main.sources=no.rutebanken.extime
    server.port=8776
    spring.jmx.enabled=true
    endpoints.jmx.enabled=true
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState,pubSub
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus

    # Camel
    camel.springboot.name=extime
    camel.springboot.shutdownTimeout=25
    camel.springboot.useMdcLogging=true
    camel.springboot.messageHistory=true

    # Avinor data set import
    avinor.airport.feed.endpoint=https://flydata.avinor.no/airportNames.asp
    avinor.airports.large=BGO,BOO,SVG,TRD
    avinor.airline.feed.endpoint=https://flydata.avinor.no/airlineNames.asp
    avinor.timetable.feed.endpoint=https://flydata.avinor.no/XmlFeedScheduled.asp
    avinor.timetable.scheduler.consumer=quartz://avinorTimetableScheduler?cron={{ .Values.avinorTimetableSchedulerCron }}
    avinor.timetable.dump.output.path=/tmp/extime/data/dump
    avinor.timetable.min.range=7
    avinor.timetable.period.months=4
    avinor.timetable.dump.enabled=false
    avinor.timetable.max.range=180
    avinor.realtime.scheduler.options=cron=2+*/3+*+*+*+*+?&trigger.timeZone=Europe/Oslo
    avinor.realtime.arrivals.timefrom=0
    avinor.realtime.arrivals.timeto=96
    avinor.realtime.departures.timefrom=0
    avinor.realtime.feed.endpoint=https://flydata.avinor.no/XmlFeed.asp
    avinor.realtime.departures.timeto=72
    netex.compressed.output.path=/tmp/extime/data/zip
    netex.generated.output.path=/tmp/extime/data/netex

    # Blobstore
    blobstore.gcs.bucket.name={{ .Values.gcp.bucketName}}
    blobstore.provider.id=21
    blobstore.blob.path=inbound/received/avi/
    blobstore.gcs.credential.path=/etc/extime-service-account/credentials.json
    blobstore.gcs.project.id={{ .Values.gcp.blobstoreProjectId }}

    # Google PubSub
    queue.upload.destination.name=MardukInboundQueue
    spring.cloud.gcp.pubsub.project-id={{ .Values.gcp.pubsubProjectId }}
    spring.cloud.gcp.pubsub.credentials.location=file:/etc/extime-service-account/credentials.json
    spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
    spring.cloud.gcp.pubsub.subscriber.executor-threads=30
    spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=36000
    entur.pubsub.subscriber.autocreate=false

    # Logging
    logging.level.com=INFO
    logging.level.org=INFO
    logging.level.no.rutebanken=INFO

kind: ConfigMap
metadata:
  name: {{ template "extime.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
