apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "extime.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
        {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "extime.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
        prometheus.io/scrape: "true"
        scheduler.alpha.kubernetes.io/affinity: |
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  { "matchExpressions":
                    [ {"key": "track", "operator": "NotIn", "values": ["build"] } ]
                  }
                ]
              }
            }
          }
      labels:
          {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -server -Xmx5000m -Dspring.config.additional-location=/etc/application-config/application.properties
                -Dfile.encoding=UTF-8
            - name: TZ
              value: Europe/Oslo
          image: eu.gcr.io/entur-system-1287/extime:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: extime
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1200m
              memory: 4750Mi
            requests:
              cpu: 500m
              memory: 4000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
            - mountPath: /etc/exchange
              name: marduk-exchange-key
            - mountPath: /etc/marduk-pubsub-account
              name: marduk-pubsub-key
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: rutebanken-registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: marduk-exchange-key
          secret:
            defaultMode: 420
            secretName: {{ .Values.gcpExchangeKeyName}}
        - name: marduk-pubsub-key
          secret:
            defaultMode: 420
            secretName: marduk-pubsub-key
        - configMap:
            defaultMode: 420
            name: extime-config
          name: application-config