apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "extime.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "extime.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
        prometheus.io/scrape: "true"
        scheduler.alpha.kubernetes.io/affinity: |
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  { "matchExpressions":
                    [ {"key": "track", "operator": "NotIn", "values": ["build"] } ]
                  }
                ]
              }
            }
          }
      labels:
    {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: extime
          image: {{ .Values.image.identifier }}
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: -server -Xmx512m -Dspring.config.additional-location=/etc/application-config/application.properties
                -Dfile.encoding=UTF-8
            - name: TZ
              value: Europe/Oslo
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/extime-service-account/credentials.json
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 800Mi
          volumeMounts:
            - mountPath: /etc/extime-service-account
              name: extime-service-account
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: extime-service-account
          secret:
            defaultMode: 420
            secretName: ror-extime-sa-key
        - configMap:
            defaultMode: 420
            name: extime-config
          name: application-config