gcp_project = "carbon-1287"
gcp_pubsub_project = "entur-ror-dev"
gcp_legacy_project = "carbon-1287"
kube_namespace = "dev"
bucket_instance_name = "marduk-exchange"
location = "europe-west1"
service_account_bucket_role = "roles/storage.admin"
