gcp_project = "entur-test-1287"
gcp_pubsub_project = "entur-ror-test"
gcp_legacy_project = "radon-1287"
kube_namespace = "staging"
bucket_instance_name = "marduk-exchange-stage"
location = "europe-west1"
service_account_bucket_role = "roles/storage.admin"
