common:
  app: extime
  shortname: extime
  team: ror
  ingress:
    enabled: false
  service:
    internalPort: 8080
  container:
    image: ${artifact.metadata.image}
    cpu: 0.5
    memory: 800
    cpuLimit: 1000m
    memoryLimit: 1000
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: extime-application
        name: application-config
  postgres:
    enabled: false
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx512m -Dspring.config.additional-location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true