apiVersion: v1
data:
  application.properties: |+
    # Spring Boot
    spring.profiles.active=gcs-blobstore
    spring.config.import=classpath:netex-static-data.yml
    spring.main.sources=no.rutebanken.extime
    server.port=8080
    # Actuator
    management.server.port=8080
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=health,prometheus
    management.endpoints.jmx.exposure.exclude=*
    # Camel
    camel.springboot.name=extime
    camel.springboot.streamCachingEnabled=false
    camel.springboot.streamCachingSpoolEnabled=true
    camel.springboot.shutdownTimeout=25
    camel.springboot.useMdcLogging=true
    camel.springboot.messageHistory=true
    # Avinor data set import
    avinor.airport.feed.endpoint=https://flydata.avinor.no/airportNames.asp
    avinor.airports.large=BGO,BOO,SVG,TRD
    avinor.airline.feed.endpoint=https://flydata.avinor.no/airlineNames.asp
    avinor.timetable.feed.endpoint=https://flydata.avinor.no/XmlFeedScheduled.asp
    avinor.timetable.scheduler.consumer=quartz://avinorTimetableScheduler?cron={{ .Values.avinorTimetableSchedulerCron }}
    avinor.timetable.dump.output.path=/tmp/extime/data/dump
    avinor.timetable.min.range=7
    avinor.timetable.period.months=4
    avinor.timetable.dump.enabled=false
    avinor.timetable.max.range=180
    avinor.realtime.scheduler.options=cron=2+*/3+*+*+*+*+?&trigger.timeZone=Europe/Oslo
    avinor.realtime.arrivals.timefrom=0
    avinor.realtime.arrivals.timeto=96
    avinor.realtime.departures.timefrom=0
    avinor.realtime.feed.endpoint=https://flydata.avinor.no/XmlFeed.asp
    avinor.realtime.departures.timeto=72
    netex.compressed.output.path=/tmp/extime/data/zip
    netex.generated.output.path=/tmp/extime/data/netex
    # Blobstore
    blobstore.gcs.marduk.container.name={{ .Values.gcp.bucketName.marduk}}
    blobstore.gcs.marduk-exchange.container.name={{ .Values.gcp.bucketName.mardukExchange}}
    blobstore.provider.id=21
    blobstore.blob.path=inbound/received/avi/
    blobstore.gcs.project.id={{ .Values.gcp.blobstoreProjectId }}
    # Google PubSub
    # project id and credential location are not set, they are retrieved automatically through the GOOGLE_APPLICATION_CREDENTIALS environment variable
    extime.pubsub.project.id={{ .Values.gcp.pubsubProjectId }}
    queue.upload.destination.name=MardukInboundQueue

kind: ConfigMap
metadata:
  name: extime-application
  namespace: "rorextime"
  labels:
    app: "extime"
    shortname: "extime"
    team: ror
