gcp_resources_project = "entur-ror-test"
gcp_pubsub_project_legacy = "entur-ror-test"
gcp_pubsub_project = "ent-marduk-tst"
bucket_instance_name = "ror-marduk-exchange-test"
extime_service_account="application@ent-rorextime-tst.iam.gserviceaccount.com"
