gcp_resources_project = "entur-ror-dev"
gcp_pubsub_project_legacy = "entur-ror-dev"
gcp_pubsub_project = "ent-marduk-dev"
bucket_instance_name = "ror-marduk-exchange-dev"
extime_service_account="application@ent-rorextime-dev.iam.gserviceaccount.com"
