gcp_resources_project = "entur-ror-prod"
gcp_pubsub_project_legacy = "entur-ror-prod"
gcp_pubsub_project = "ent-marduk-prd"
bucket_instance_name = "ror-marduk-exchange-production"
extime_service_account="application@ent-rorextime-prd.iam.gserviceaccount.com"